version: '3.8'
services:
    postgres:
        image: postgres:15.1-alpine
        container_name: postgres
        restart: always
        volumes:
            - postgres_volume:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5431:5432"
    server:
        container_name: server
        build: ./Server-Mac
        depends_on:
            - postgres
        ports:
            - "5085:5085"
    frontend:
        container_name: frontend
        build: ./client
        ports:
            - "80:80"
    
volumes:
    postgres_volume:
