version: '3.8'
services:
    server:
        platform: linux/amd64
        container_name: server
        build: ./Server-Mac
        ports:
            - "5085:5085"
    frontend:
        platform: linux/amd64
        container_name: frontend
        build: ./client
        ports:
            - "80:80"
    
volumes:
    postgres_volume:
