apiVersion: v1
kind: Service
metadata:
  name: zadanie-postgres
  labels:
    app: zadanie
spec:
  ports:
    - port: 5432
  selector:
    app: zadanie
    tier: postgres
    
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data/db"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: zadanie
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1 # for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: zadanie-postgres
  labels:
    app: zadanie
spec:
  selector:
    matchLabels:
      app: zadanie
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zadanie
        tier: postgres
    spec:
      containers:
      - image: postgres:alpine
        name: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        livenessProbe:
          tcpSocket:
            port: 5432
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim