apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk-pvc
spec:
  storageClassName: azuredisk-standard-retain
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
