kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azuredisk-standard-retain
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  storageaccounttype: Standard
  kind: managed